# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: odin_deployer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'odin_deployer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13odin_deployer.proto\x12\x15\x64ream11.od.service.v1\"q\n,GetLatestCatalogueReleaseByRepositoryRequest\x12\x1d\n\ngithub_url\x18\x01 \x01(\tR\tgithubUrl\x12\x15\n\x08\x63oncrete\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x0b\n\t_concrete\"\xbd\x01\n-GetLatestCatalogueReleaseByRepositoryResponse\x12&\n\x0cservice_name\x18\x01 \x01(\tH\x00R\x0bserviceName\x88\x01\x01\x12\x14\n\x07version\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\"\n\ncreated_at\x18\x03 \x01(\tH\x02R\tcreatedAt\x88\x01\x01\x42\x0f\n\r_service_nameB\n\n\x08_versionB\r\n\x0b_created_at2\xc7\x01\n\x0eServiceService\x12\xb4\x01\n%GetLatestCatalogueReleaseByRepository\x12\x43.dream11.od.service.v1.GetLatestCatalogueReleaseByRepositoryRequest\x1a\x44.dream11.od.service.v1.GetLatestCatalogueReleaseByRepositoryResponse\"\x00\x42!\n\x1d\x63om.dream11.odin.grpc.serviceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'odin_deployer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.dream11.odin.grpc.serviceP\001'
  _globals['_GETLATESTCATALOGUERELEASEBYREPOSITORYREQUEST']._serialized_start=46
  _globals['_GETLATESTCATALOGUERELEASEBYREPOSITORYREQUEST']._serialized_end=159
  _globals['_GETLATESTCATALOGUERELEASEBYREPOSITORYRESPONSE']._serialized_start=162
  _globals['_GETLATESTCATALOGUERELEASEBYREPOSITORYRESPONSE']._serialized_end=351
  _globals['_SERVICESERVICE']._serialized_start=354
  _globals['_SERVICESERVICE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
