"""GitHub API: parse PR URLs and fetch PR file diffs.

Uses GITHUB_PAT env var. stdlib-only (no extra deps)."""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request


_PR_URL = re.compile(
    r"(?:https?://github\.com/|git@github\.com:)"
    r"(?P<owner>[^/]+)/"
    r"(?P<repo>[^/.\s]+?)"
    r"(?:\.git)?"
    r"/pull/(?P<num>\d+)"
)

# Files we never bother sending to the LLM — they're noise for impact
# classification (autogenerated, huge, or trivially unrelated to handler code).
_SKIP_FILE_RE = re.compile(
    r"(^|/)("
    r"package-lock\.json|yarn\.lock|pnpm-lock\.yaml|"
    r"poetry\.lock|Pipfile\.lock|"
    r"go\.sum|"
    r"Cargo\.lock|"
    r"composer\.lock"
    r")$"
)


_TEST_DIRS = {"tests", "test", "__tests__", "spec", "specs", "e2e", "cypress"}


def _is_test_file(path: str) -> bool:
    """True if the path looks like a test file by convention.

    Test changes don't affect deploy-impact for prod handlers, so we strip
    them up-front rather than relying on the LLM to ignore them."""
    parts = path.split("/")
    name = parts[-1] if parts else path
    # Any directory component is a test dir
    for p in parts[:-1]:
        if p in _TEST_DIRS:
            return True
    # Filename conventions across languages
    if name.startswith("test_"):
        return True
    if name.endswith("_test.py") or name.endswith("_test.go") or name.endswith("_test.rs"):
        return True
    if ".test." in name or ".spec." in name:        # foo.test.ts, foo.spec.tsx
        return True
    if name.endswith("_spec.rb"):
        return True
    if name.endswith("Test.java") or name.endswith("IT.java"):
        return True
    return False


class GitHubError(RuntimeError):
    pass


def parse_pr_url(url: str) -> tuple[str, str, int]:
    """Extract (owner, repo, pr_number). Raises ValueError if not a PR URL."""
    m = _PR_URL.search(url.strip())
    if not m:
        raise ValueError(f"not a pull-request URL: {url!r}")
    return m.group("owner"), m.group("repo"), int(m.group("num"))


def fetch_pr_meta(owner: str, repo: str, pr_number: int) -> dict:
    """Returns the GitHub PR object. We need head.sha + head.ref +
    head.repo.full_name (which differs from base for fork PRs)."""
    pat = os.getenv("GITHUB_PAT")
    if not pat:
        raise GitHubError("GITHUB_PAT env var is not set")

    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": f"Bearer {pat}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "cartograph-pr-impact-agent",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode(errors="replace") if e.fp else ""
        raise GitHubError(
            f"GitHub API {e.code} for {owner}/{repo} PR #{pr_number}: {body[:200]}"
        ) from e
    except urllib.error.URLError as e:
        raise GitHubError(f"GitHub API unreachable: {e.reason}") from e


def fetch_pr_files(owner: str, repo: str, pr_number: int,
                   pages: int = 5, per_page: int = 100) -> list[dict]:
    """Returns list of {filename, status, additions, deletions, patch}.
    Walks up to `pages` pages so very large PRs aren't silently truncated."""
    pat = os.getenv("GITHUB_PAT")
    if not pat:
        raise GitHubError("GITHUB_PAT env var is not set")

    out: list[dict] = []
    for page in range(1, pages + 1):
        url = (f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"
               f"/files?per_page={per_page}&page={page}")
        req = urllib.request.Request(
            url,
            headers={
                "Authorization": f"Bearer {pat}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
                "User-Agent": "cartograph-pr-impact-agent",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=20) as resp:
                page_data = json.loads(resp.read().decode())
        except urllib.error.HTTPError as e:
            body = e.read().decode(errors="replace") if e.fp else ""
            raise GitHubError(
                f"GitHub API {e.code} for {owner}/{repo} PR #{pr_number}: {body[:200]}"
            ) from e
        except urllib.error.URLError as e:
            raise GitHubError(f"GitHub API unreachable: {e.reason}") from e

        if not page_data:
            break
        out.extend(page_data)
        if len(page_data) < per_page:
            break
    return out


def build_diff_text(files: list[dict],
                    max_chars: int = 60_000) -> tuple[str, list[str], list[str]]:
    """Concatenate per-file patches into one diff blob, with skip + truncation
    accounting.

    Returns (diff_text, included_filenames, skipped_with_reason)."""
    parts: list[str] = []
    included: list[str] = []
    skipped: list[str] = []
    total = 0

    for f in files:
        name = f.get("filename", "<unknown>")
        if _SKIP_FILE_RE.search(name):
            skipped.append(f"{name} — lockfile, skipped")
            continue
        if _is_test_file(name):
            skipped.append(f"{name} — test file, skipped")
            continue
        patch = f.get("patch")
        if not patch:
            status = f.get("status", "?")
            skipped.append(f"{name} — no patch (status={status}, likely binary/large)")
            continue
        chunk = f"--- a/{name}\n+++ b/{name}\n{patch}\n"
        if total + len(chunk) > max_chars:
            skipped.append(f"{name} — truncated (diff budget exceeded)")
            continue
        parts.append(chunk)
        included.append(name)
        total += len(chunk)

    return "\n".join(parts), included, skipped
